--cau1

CREATE DATABASE QLBH


CREATE TABLE KHACHHANG (
	MAKH CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY
);
CREATE TABLE NHANVIEN (
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
);
CREATE TABLE SANPHAM (
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
);
CREATE TABLE HOADON (
	SOHD INT PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
CREATE TABLE CTHD (
	SOHD INT,
	MASP CHAR(4),
	SL INT
	PRIMARY KEY (SOHD, MASP)
	FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

--cau2
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20);
--cau3
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT;
--cau4
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);
--cau5
ALTER TABLE SANPHAM DROP COLUMN GHICHU;
--cau6
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20);
--cau7
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));
--cau8
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_GIA CHECK (GIA >= 500);
--cau9
ALTER TABLE CTHD
ADD CONSTRAINT CHK_SL CHECK (SL >= 1);
--cau10
ALTER TABLE KHACHHANG
ADD CONSTRAINT CHK_NGDK CHECK (NGDK > NGSINH);