--Nguyễn Lê Hưng
--23520567
--IT004.P113.2

--Lab 4.2 - InClass - QLGV

--Bài tập 1------------------
--19.
SELECT MAKHOA, TENKHOA
FROM KHOA
WHERE NGTLAP IN (SELECT TOP 1 NGTLAP
					FROM KHOA
					ORDER BY NGTLAP ASC);

-- 20.
SELECT COUNT(*) AS 'GS or PGS'
FROM GIAOVIEN
WHERE HOCHAM IN ('GS','PGS')

-- 21.
SELECT MAKHOA, HOCVI, COUNT(*) AS 'So Luong'
FROM GIAOVIEN
GROUP BY MAKHOA, HOCVI;

-- 22.
SELECT MAMH, KQUA, COUNT(*) AS 'Ket Qua'
FROM KETQUATHI
GROUP BY MAMH, KQUA 
ORDER BY MAMH;

-- 23.
SELECT G.MAGV, G.HOTEN 
FROM GIAOVIEN G INNER JOIN LOP L ON G.MAGV = L.MAGVCN
				INNER JOIN GIANGDAY G2 ON G2.MALOP = L.MALOP AND G2.MAGV = G.MAGV;

-- 24.
SELECT HO,TEN
FROM HOCVIEN 
WHERE MAHV IN (SELECT TRGLOP
				FROM LOP 
				WHERE SISO IN (SELECT MAX(SISO)
								FROM LOP));

-- 25.
SELECT HO, TEN
FROM HOCVIEN
WHERE MAHV IN (SELECT TRGLOP
				FROM LOP
				WHERE TRGLOP IN (SELECT MAHV
								FROM KETQUATHI
								WHERE KQUA = 'Khong Dat'
								GROUP BY MAHV
								HAVING COUNT(DISTINCT MAMH) > 3));

--Bài tập 2-----------------------------
-- 26.
SELECT TOP 1 WITH TIES H.MAHV, H.HO, H.TEN
FROM HOCVIEN H INNER JOIN KETQUATHI K ON H.MAHV = K.MAHV 
WHERE K.DIEM >= 9
GROUP BY H.MAHV, H.HO, H.TEN 
ORDER BY COUNT(*) DESC;

-- 27.

-- 28.
SELECT MAGV, COUNT(DISTINCT MAMH) 'So Mon Hoc', COUNT(DISTINCT MALOP) 'So Lop'
FROM GIANGDAY
GROUP BY MAGV 

-- 29.
SELECT A.HOCKY, A.NAM, A.MAGV, g.HOTEN 
FROM GIAOVIEN G,
(
	SELECT G2.HOCKY , G2.NAM, G2.MAGV, RANK() OVER (PARTITION BY G2.HOCKY, G2.NAM ORDER BY COUNT(*) DESC) AS XEPHANG
	FROM GIANGDAY G2
	GROUP BY G2.HOCKY, G2.NAM, G2.MAGV
) AS A
WHERE A.MAGV = G.MAGV AND XEPHANG = 1
ORDER BY A.NAM, A.HOCKY;

-- 30.
SELECT TOP 1 WITH TIES M.MAMH, M.TENMH
FROM MONHOC M INNER JOIN KETQUATHI k 
ON M.MAMH = K.MAMH 
WHERE K.LANTHI = 1 AND K.KQUA = 'Khong Dat'
GROUP BY M.MAMH, M.TENMH 
ORDER BY COUNT(*) DESC;

-- 31.
SELECT DISTINCT H.MAHV, HO + ' ' + TEN 'Ho va Ten'
FROM HOCVIEN H 
JOIN KETQUATHI K 
ON H.MAHV = K.MAHV 
WHERE NOT EXISTS (
	SELECT *
	FROM KETQUATHI K2 
	WHERE K2.MAHV = H.MAHV AND K2.LANTHI = 1 AND K2.KQUA = 'Khong Dat'
);

-- 32.

-- 33.

-- 34.

-- 35.
